---
rg-scheduler:
  channel_name: 'mban'
  int_weekday: 7
  int_freq: 1
  str_time: "17:00"
  sec_sleep: 10
  group_size: 2

rg-participation-scheduler:
  channel_name: 'mban'
  int_weekday: 5
  int_freq: 1
  str_time: "21:00"
  sec_sleep: 10